# Generated by Django 4.2.7 on 2023-12-12 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("major", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "title",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=1000)),
                ("primary_theme", models.CharField(max_length=100)),
                ("secondary_theme", models.CharField(max_length=100)),
                ("file", models.FileField(null=True, upload_to="files/")),
                ("audience", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Create",
            fields=[
                (
                    "name",
                    models.ForeignKey(
                        db_column="name",
                        default="Student",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="hstem.author",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "title",
                    models.ForeignKey(
                        db_column="title",
                        default="A Project",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hstem.project",
                    ),
                ),
            ],
        ),
    ]
