# Generated by Django 4.2.7 on 2023-11-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hstem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
