# Generated by Django 4.2.7 on 2023-12-13 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="primary_theme",
            new_name="cohort",
        ),
        migrations.RemoveField(
            model_name="project",
            name="secondary_theme",
        ),
    ]
