# Generated by Django 4.2.6 on 2023-11-08 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0002_rename_authors_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "school",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "title",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=1000)),
                ("primary_theme", models.CharField(max_length=100)),
                ("secondary_theme", models.CharField(max_length=100)),
                ("audience", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="author",
            name="id",
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("is_public", models.BooleanField()),
                ("type", models.CharField(max_length=50)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hstem.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Create",
            fields=[
                ("date", models.DateField()),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="hstem.author",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hstem.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="hstem.department",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hstem.project",
                    ),
                ),
            ],
        ),
    ]
