# Generated by Django 4.2.6 on 2023-11-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0003_department_project_remove_author_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Files",
            new_name="File",
        ),
    ]
