# Generated by Django 4.2.6 on 2023-11-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0004_rename_files_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="year",
            field=models.CharField(max_length=10),
        ),
    ]
