# Generated by Django 4.2.7 on 2023-12-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0005_alter_author_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsor",
            name="school",
        ),
        migrations.RemoveField(
            model_name="sponsor",
            name="title",
        ),
        migrations.RemoveField(
            model_name="project",
            name="link_to_url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="thumbnail_url",
        ),
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Sponsor",
        ),
    ]
