# Generated by Django 4.2.7 on 2023-12-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0005_alter_create_name_alter_create_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="type",
            field=models.CharField(
                choices=[
                    ("img", "Image"),
                    ("vid", "Video"),
                    ("pdf", "PDF"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
