# Generated by Django 4.2.6 on 2023-12-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0006_remove_sponsor_school_remove_sponsor_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="file",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
