# Generated by Django 4.2.7 on 2023-12-13 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0006_alter_create_name_alter_create_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="create",
            name="title",
            field=models.ForeignKey(
                db_column="title",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="hstem.project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cohort",
            field=models.CharField(max_length=10),
        ),
    ]
