# Generated by Django 4.2.7 on 2023-12-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0007_alter_create_title_alter_project_cohort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cohort",
            field=models.CharField(max_length=100),
        ),
    ]
