# Generated by Django 4.2.7 on 2023-12-13 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0008_alter_project_cohort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="create",
            name="name",
            field=models.ForeignKey(
                db_column="name",
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="hstem.author",
            ),
        ),
    ]
