# Generated by Django 4.2.7 on 2023-12-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0008_remove_create_date_create_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="file",
            field=models.FileField(null=True, upload_to="files/"),
        ),
        migrations.DeleteModel(
            name="File",
        ),
    ]
