# Generated by Django 4.2.7 on 2023-12-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0009_alter_create_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(max_length=5000),
        ),
    ]
