# Generated by Django 4.2.7 on 2023-12-12 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0009_project_file_delete_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="create",
            old_name="name",
            new_name="name_id",
        ),
        migrations.RenameField(
            model_name="create",
            old_name="title",
            new_name="title_id",
        ),
    ]
