# Generated by Django 4.2.7 on 2023-12-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0010_alter_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="audience",
            field=models.CharField(
                choices=[
                    ("students", "Students"),
                    ("faculty", "Faculty"),
                    ("5c", "5C"),
                    ("other", "Other"),
                ],
                default="students",
                max_length=100,
            ),
        ),
    ]
