# Generated by Django 4.2.7 on 2023-12-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hstem", "0011_alter_project_audience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
